---
version: 2
jobs:
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: yarn
      - run: yarn test
  node-12:
    <<: *test
    docker:
      - image: node:12
  node-10:
    <<: *test
    docker:
      - image: node:10
  release:
    <<: *test
    steps:
      - checkout
      - add_ssh_keys
      - run: yarn
      - run: ./node_modules/.bin/semantic-release

workflows:
  version: 2
  "@oclif/semantic-release":
    jobs:
      - node-latest
      - node-12
      - node-10
      - release:
          context: org-global
          filters:
            branches: {only: master}
          requires:
            - node-latest
